### ISSUE TITLE
Porting server code to Go instead of Elixir?

### ISSUE THREAD

**Issue by apeacox** [leonmaia/atom-remote-pair-server#1]
I love Elixir but, perhaps, a tool like this might fit well with Go because it lets you deploy a single, cross-platform binary that can be shared across workstations/servers. just like ngrok.

what do you think?

**Comment by brunobatista** [comment]
+1 Go

**Comment by leonmaia** [comment]
@apeacox @brunobatista I think it's great! We have to create a discussion about this in the future, on the present date we are focusing on the stabilization of the client and on a few features that we find would give a better experience to the user. 

ps: This repository is not being updated anymore, we have ported this server repo and the client to this organization account [motepair](http://github.com/motepair). I will create a new issue on the server repository so we can discuss it on a later date.
